services:
  productapp:
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - productapp-mysql
      - productapp-redis

  productapp-mysql:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=productapp
      - MYSQL_ROOT_PASSWORD=root

  productapp-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    depends_on:
      - productapp

  productapp-redis:
    image: redis:7.0-alpine
    expose:
      - "6379"
